version: '3.5'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database:app_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: "mariadb:10.5.8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgTutorias
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
